import type { Metadata } from "next";
import { Noto_Sans, Sora } from "next/font/google";
import "./globals.scss";

const NotoSans = Noto_Sans({
    weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const sora = Sora({
    weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>{children}</body>
        </html>
    );
}
